from pathlib import Path
import re

path = Path('frontend/src/pages/BillingWorkspace.jsx')
source = path.read_text()

nav_pattern = re.compile(r"const nav = \[\n.*?\n\];", re.S)
new_nav = '''const nav = [
  ['overview', 'Overview', 'dashboard'],
  ['subscribers', 'Subscribers', 'users'],
  ['services', 'PPPoE', 'broadband'],
  ['hotspot', 'Hotspot', 'hotspot'],
  ['agents', 'Agents', 'bot'],
  ['invoices', 'Invoices', 'receipt'],
  ['payments', 'Payments', 'wallet'],
  ['vouchers', 'Vouchers', 'ticket'],
  ['routers', 'Routers', 'router'],
  ['radius', 'RADIUS', 'radius'],
  ['tr069', 'TR-069 & ONTs', 'antenna'],
  ['communication', 'Communication', 'chat'],
  ['reports', 'Reports', 'chart'],
];'''
source, count = nav_pattern.subn(new_nav, source, count=1)
if count != 1:
    raise SystemExit('Could not replace billing navigation icon map')

old_aside = '''    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[260px] flex-col overflow-y-auto overflow-x-hidden overscroll-contain border-r border-slate-100 bg-white px-4 py-7 text-slate-500 shadow-[8px_0_30px_rgba(15,23,42,.025)] transition-transform duration-300 ${open ? 'translate-x-0' : '-translate-x-full'} ${sidebarCollapsed ? 'lg:-translate-x-full' : 'lg:translate-x-0'}`}>
      <div className="flex items-center gap-2 px-4"><div className={`text-sm font-black uppercase tracking-[.1em] ${darkMode ? 'text-slate-100' : 'text-slate-900'}`}>POLYIZON</div><div className={`border-l pl-2 text-[10px] font-extrabold uppercase tracking-[.16em] ${darkMode ? 'border-slate-600 text-slate-400' : 'border-slate-300 text-slate-600'}`}>BILLING SYSTEM</div></div>
      <div className="mt-8 space-y-5 pb-5">'''
new_aside = '''    <aside
      style={{ fontFamily: '\"Segoe UI Variable Display\", \"Avenir Next\", \"Plus Jakarta Sans\", Inter, ui-sans-serif, system-ui, sans-serif' }}
      className={`fixed inset-y-0 left-0 z-40 flex w-[218px] flex-col overflow-y-auto overflow-x-hidden overscroll-contain border-r border-slate-100 bg-white px-2.5 py-3 text-slate-500 shadow-[8px_0_30px_rgba(15,23,42,.035)] transition-transform duration-300 sm:w-[232px] sm:px-3 lg:w-[260px] lg:px-4 lg:py-7 ${open ? 'translate-x-0' : '-translate-x-full'} ${sidebarCollapsed ? 'lg:-translate-x-full' : 'lg:translate-x-0'}`}
    >
      <div className="flex items-center gap-1.5 px-2 py-1 lg:gap-2 lg:px-4 lg:py-0">
        <div className={`text-[11px] font-extrabold uppercase tracking-[.08em] lg:text-sm lg:font-black lg:tracking-[.1em] ${darkMode ? 'text-slate-100' : 'text-slate-900'}`}>POLYIZON</div>
        <div className={`border-l pl-1.5 text-[7px] font-bold uppercase tracking-[.12em] lg:pl-2 lg:text-[10px] lg:font-extrabold lg:tracking-[.16em] ${darkMode ? 'border-slate-600 text-slate-400' : 'border-slate-300 text-slate-500'}`}>BILLING</div>
      </div>
      <div className="mt-3 space-y-1 pb-2 lg:mt-8 lg:space-y-5 lg:pb-5">'''
if old_aside not in source:
    raise SystemExit('Could not locate mobile billing sidebar shell')
source = source.replace(old_aside, new_aside, 1)

source = source.replace(
    '              <div className="px-4 text-[10px] font-black uppercase tracking-[.18em] text-slate-400">',
    '              <div className="hidden px-4 text-[10px] font-black uppercase tracking-[.18em] text-slate-400 lg:block">',
    1,
)
# Apply to every group heading occurrence generated by the map (the JSX text appears once).
source = source.replace(
    '              <nav className="mt-2 space-y-1">',
    '              <nav className="mt-1 grid grid-cols-2 gap-1 lg:mt-2 lg:block lg:space-y-1">',
    1,
)

old_button_class = '''                      className={`flex w-full items-center gap-3 rounded-r-xl px-4 py-2.5 text-left text-sm font-bold transition ${
                        tab === key
                          ? 'border-l-[3px] border-emerald-500 bg-emerald-50 text-emerald-600'
                          : 'border-l-[3px] border-transparent text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                      }`}'''
new_button_class = '''                      className={`flex min-w-0 w-full items-center gap-1.5 rounded-xl px-1.5 py-1.5 text-left text-[9.5px] font-semibold tracking-[-.015em] transition sm:gap-2 sm:px-2 sm:py-2 sm:text-[10px] lg:gap-3 lg:rounded-r-xl lg:px-4 lg:py-2.5 lg:text-sm lg:font-bold ${
                        tab === key
                          ? 'bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-100 lg:border-l-[3px] lg:border-emerald-500 lg:ring-0'
                          : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900 lg:border-l-[3px] lg:border-transparent'
                      }`}'''
if old_button_class not in source:
    raise SystemExit('Could not locate sidebar navigation button styles')
source = source.replace(old_button_class, new_button_class, 1)

old_icon_span = '                      <span className="flex h-6 w-6 shrink-0 items-center justify-center text-slate-500">'
new_icon_span = '''                      <span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-lg transition sm:h-7 sm:w-7 lg:h-6 lg:w-6 lg:rounded-none lg:bg-transparent ${
                        tab === key
                          ? 'bg-emerald-100 text-emerald-700'
                          : 'bg-slate-50 text-slate-500'
                      }`}>'''
if old_icon_span not in source:
    raise SystemExit('Could not locate sidebar icon wrapper')
source = source.replace(old_icon_span, new_icon_span, 1)

old_footer = '''      <div className="mt-auto border-t border-slate-100 px-3 pt-5"><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-100 text-xs font-black text-emerald-700">{(admin.name || 'B').slice(0, 1).toUpperCase()}</div><div className="min-w-0"><div className="truncate text-xs font-bold text-slate-800">{admin.name || 'Billing admin'}</div><div className="truncate text-[11px] text-slate-400">{admin.client_business_name || admin.client_name}</div></div></div><button type="button" onClick={logout} className="mt-4 flex items-center gap-2 text-xs font-bold text-slate-400 hover:text-rose-600"><svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4 fill-none stroke-current" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"><path d="M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-6" /></svg><span>Sign out</span></button></div>'''
new_footer = '''      <div className="mt-auto border-t border-slate-100 px-1 pt-2 lg:px-3 lg:pt-5">
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-xl bg-emerald-100 text-[9px] font-black text-emerald-700 lg:h-9 lg:w-9 lg:rounded-full lg:text-xs">{(admin.name || 'B').slice(0, 1).toUpperCase()}</div>
          <div className="min-w-0 flex-1">
            <div className="truncate text-[10px] font-semibold text-slate-800 lg:text-xs lg:font-bold">{admin.name || 'Billing admin'}</div>
            <div className="hidden truncate text-[11px] text-slate-400 lg:block">{admin.client_business_name || admin.client_name}</div>
          </div>
        </div>
        <button type="button" onClick={logout} className="mt-2 flex h-7 items-center gap-1.5 rounded-lg px-1.5 text-[9px] font-semibold text-slate-400 transition hover:bg-rose-50 hover:text-rose-600 lg:mt-4 lg:h-auto lg:px-0 lg:text-xs lg:font-bold">
          <svg viewBox="0 0 24 24" aria-hidden="true" className="h-3.5 w-3.5 fill-none stroke-current lg:h-4 lg:w-4" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"><path d="M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-6" /></svg>
          <span>Sign out</span>
        </button>
      </div>'''
if old_footer not in source:
    raise SystemExit('Could not locate billing sidebar footer')
source = source.replace(old_footer, new_footer, 1)

nav_icon_pattern = re.compile(r"function NavIcon\(\{ kind \}\) \{.*?\}function MobileDock", re.S)
new_nav_icon = r'''function NavIcon({ kind }) {
  const paths = {
    home: <><path d="M4 10.5 12 4l8 6.5" /><path d="M6.5 9.5V20h11V9.5" /><path d="M10 20v-5h4v5" /></>,
    dashboard: <><rect x="3.5" y="3.5" width="7" height="7" rx="2" /><rect x="13.5" y="3.5" width="7" height="4.5" rx="2" /><rect x="3.5" y="13.5" width="7" height="7" rx="2" /><rect x="13.5" y="10.5" width="7" height="10" rx="2" /></>,
    clients: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20a5.5 5.5 0 0 1 11 0" /><circle cx="17.5" cy="9.5" r="2.2" /><path d="M16 15.5a4.5 4.5 0 0 1 4.5 4.5" /></>,
    users: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20a5.5 5.5 0 0 1 11 0" /><circle cx="17.5" cy="9.5" r="2.2" /><path d="M16 15.5a4.5 4.5 0 0 1 4.5 4.5" /></>,
    broadband: <><path d="M4 16a8 8 0 0 1 16 0" /><path d="M7 16a5 5 0 0 1 10 0" /><path d="m12 16 3-5" /><circle cx="12" cy="16" r="1.4" /></>,
    hotspot: <><path d="M4 9a12 12 0 0 1 16 0" /><path d="M7.5 12.5a7 7 0 0 1 9 0" /><path d="M10.5 16a2.5 2.5 0 0 1 3 0" /><circle cx="12" cy="19" r="1" fill="currentColor" stroke="none" /></>,
    bot: <><rect x="5" y="7" width="14" height="12" rx="3" /><path d="M12 3v4" /><circle cx="12" cy="3" r="1" /><path d="M9 12h.01M15 12h.01M9 16h6" /></>,
    receipt: <><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z" /><path d="M9 8h6M9 12h6M9 16h4" /></>,
    invoices: <><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z" /><path d="M9 8h6M9 12h6M9 16h4" /></>,
    wallet: <><path d="M4 7h14a2 2 0 0 1 2 2v9H6a2 2 0 0 1-2-2V7Z" /><path d="M4 8V6a2 2 0 0 1 2-2h11" /><path d="M15 12h6v4h-6a2 2 0 1 1 0-4Z" /></>,
    payments: <><rect x="3" y="6" width="18" height="12" rx="3" /><path d="M3 10h18M7 15h4" /></>,
    ticket: <><path d="M4 7a2 2 0 0 0 2-2h12a2 2 0 0 0 2 2v2a2.5 2.5 0 0 0 0 5v3a2 2 0 0 0-2 2H6a2 2 0 0 0-2-2v-3a2.5 2.5 0 0 0 0-5V7Z" /><path d="M12 8v8" /></>,
    voucher: <><path d="M4 7a2 2 0 0 0 2-2h12a2 2 0 0 0 2 2v2a2.5 2.5 0 0 0 0 5v3a2 2 0 0 0-2 2H6a2 2 0 0 0-2-2v-3a2.5 2.5 0 0 0 0-5V7Z" /><path d="M12 8v8" /></>,
    vouchers: <><path d="M4 7a2 2 0 0 0 2-2h12a2 2 0 0 0 2 2v2a2.5 2.5 0 0 0 0 5v3a2 2 0 0 0-2 2H6a2 2 0 0 0-2-2v-3a2.5 2.5 0 0 0 0-5V7Z" /><path d="M12 8v8" /></>,
    router: <><rect x="3" y="9" width="18" height="9" rx="2.5" /><path d="M7 9 5 5M17 9l2-4" /><circle cx="7" cy="14" r="1" fill="currentColor" stroke="none" /><circle cx="11" cy="14" r="1" fill="currentColor" stroke="none" /><path d="M15 14h3" /></>,
    network: <><rect x="3" y="9" width="18" height="9" rx="2.5" /><path d="M7 9 5 5M17 9l2-4" /><circle cx="7" cy="14" r="1" fill="currentColor" stroke="none" /><circle cx="11" cy="14" r="1" fill="currentColor" stroke="none" /><path d="M15 14h3" /></>,
    radius: <><circle cx="12" cy="12" r="8" /><circle cx="12" cy="12" r="4" /><path d="M12 12 18 7" /><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none" /></>,
    antenna: <><path d="M12 6v15M8.5 21h7" /><path d="m9 12 3-6 3 6" /><path d="M6.5 9a7 7 0 0 1 11 0M4 6a11 11 0 0 1 16 0" /></>,
    chat: <><path d="M5 5h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H10l-5 3v-3H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z" /><path d="M8 10h8M8 14h5" /></>,
    chart: <><path d="M4 20V10M10 20V4M16 20v-7M22 20V7" /><path d="M2 20h22" /></>,
    reports: <><path d="M4 20V10M10 20V4M16 20v-7M22 20V7" /><path d="M2 20h22" /></>,
    more: <><circle cx="6" cy="6" r="1.3" /><circle cx="12" cy="6" r="1.3" /><circle cx="18" cy="6" r="1.3" /><circle cx="6" cy="12" r="1.3" /><circle cx="12" cy="12" r="1.3" /><circle cx="18" cy="12" r="1.3" /><circle cx="6" cy="18" r="1.3" /><circle cx="12" cy="18" r="1.3" /><circle cx="18" cy="18" r="1.3" /></>,
    add: <path d="M12 5v14M5 12h14" />,
    packages: <><path d="m12 3 8 4.5-8 4.5-8-4.5L12 3Z" /><path d="m4 12 8 4.5 8-4.5M4 16.5l8 4.5 8-4.5" /></>,
  };

  return (
    <svg
      viewBox="0 0 24 24"
      aria-hidden="true"
      className="h-[18px] w-[18px] fill-none stroke-current lg:h-5 lg:w-5"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      {paths[kind] || paths.more}
    </svg>
  );
}
function MobileDock'''
source, count = nav_icon_pattern.subn(new_nav_icon, source, count=1)
if count != 1:
    raise SystemExit('Could not replace navigation icon set')

required = [
    'w-[218px]',
    'grid-cols-2',
    'Segoe UI Variable Display',
    "['reports', 'Reports', 'chart']",
    'function NavIcon({ kind })',
]
for token in required:
    if token not in source:
        raise SystemExit(f'Missing expected mobile sidebar token: {token}')

path.write_text(source)
