import http from 'node:http';
import { config, validateConfig } from './config.js';
import { CallRegistry } from './calls.js';
import { AriClient } from './ari.js';
import { RtpEchoBridge } from './media.js';
const registry = new CallRegistry(); const startupErrors = validateConfig(); const mediaBridge = new RtpEchoBridge({ host: '127.0.0.1', port: Number(process.env.EXTERNAL_MEDIA_PORT || 12000) }); const ari = new AriClient();
function json(res,status,body){const payload=JSON.stringify(body);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(payload),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'});res.end(payload)}
function authorized(req){const supplied=req.headers.authorization||'',expected=`Bearer ${config.sharedSecret}`;const a=Buffer.from(supplied),b=Buffer.from(expected);if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i+=1)r|=a[i]^b[i];return r===0}
async function handleAri(event){if(event.type!=='StasisStart'||!event.channel?.id||event.channel.name?.startsWith('UnicastRTP/'))return;const call=registry.create({channelId:event.channel.id,state:'media-bridging'});try{const bridge=await ari.createBridge();const media=await ari.createExternalMedia(config.externalMediaHost);await ari.addToBridge(bridge.id,[event.channel.id,media.id]);registry.update(call.id,{state:'media-connected',bridgeId:bridge.id,mediaChannelId:media.id})}catch(error){registry.update(call.id,{state:'media-failed',error:error.message})}}
const server=http.createServer((req,res)=>{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/health')return json(res,startupErrors.length?503:200,{status:startupErrors.length?'misconfigured':'ok',service:'nexa-voice-gateway',calls:registry.list().length,mediaBridge:mediaBridge.started?'listening':'stopped',errors:startupErrors});if(!authorized(req))return json(res,401,{error:'Unauthorized'});if(req.method==='GET'&&url.pathname==='/v1/calls')return json(res,200,{calls:registry.list()});return json(res,404,{error:'Not found'})});
if(process.argv[1]&&process.argv[1].endsWith('server.js')){mediaBridge.start();ari.connect(handleAri).on('error',(error)=>console.error(`ARI connection error: ${error.message}`));server.listen(config.port,config.host,()=>console.log(`nexa-voice-gateway listening on ${config.host}:${config.port}`))}
export {server,registry,mediaBridge};